//! Polish Designer — server-authoritative design program for Polish UIs.
//! Compose components, switch themes, watch the live preview, export real Rust code.
//! State lives on the server (projection law); the browser only displays.

use std::sync::Mutex;
use axum::{
    Router,
    extract::{Path, State},
    response::{Html, IntoResponse, Redirect, Response},
    routing::{get, post},
};
use std::sync::Arc;
use polish_core::escape_html;
use polish_style::{BuiltinTheme, StyleSheet};

#[derive(Clone, Copy, PartialEq, Debug)]
enum Kind { Navbar, Hero, Card, Form, Button, Table, Footer }

impl Kind {
    fn all() -> [Kind; 7] { [Kind::Navbar, Kind::Hero, Kind::Card, Kind::Form, Kind::Button, Kind::Table, Kind::Footer] }
    fn name(&self) -> &'static str {
        match self { Kind::Navbar=>"Navbar", Kind::Hero=>"Hero", Kind::Card=>"Card", Kind::Form=>"Form", Kind::Button=>"Button", Kind::Table=>"Table", Kind::Footer=>"Footer" }
    }
    fn from(s: &str) -> Option<Kind> { Kind::all().into_iter().find(|k| k.name().eq_ignore_ascii_case(s)) }
    fn html(&self) -> String {
        match self {
            Kind::Navbar => r##"<nav class="p-header" style="display:flex;align-items:center;gap:2rem;padding:1rem 2rem;border-bottom:1px solid var(--p-border)"><span class="p-header-title" style="font-weight:700">Brand</span><div style="display:flex;gap:1.5rem"><a href="#" class="p-nav-link">Home</a><a href="#" class="p-nav-link">Pricing</a><a href="#" class="p-nav-link">Docs</a></div></nav>"##.into(),
            Kind::Hero => r##"<section style="padding:4rem 2rem;text-align:center"><h1 style="font-size:2.2rem;margin:0 0 .5rem">Your product headline</h1><p style="color:var(--p-text2);max-width:40rem;margin:0 auto 1.5rem">One sentence that says what it does and why it matters.</p><button class="p-btn p-btn-primary">Get Started</button></section>"##.into(),
            Kind::Card => r#"<div class="p-card" style="max-width:28rem;margin:1rem auto;padding:1.5rem"><h3 style="margin:0 0 .5rem">Card title</h3><p style="color:var(--p-text2);margin:0">Supporting copy for this card. Server-rendered, XSS-safe.</p></div>"#.into(),
            Kind::Form => r#"<div class="p-card" style="max-width:28rem;margin:1rem auto;padding:1.5rem"><h3 style="margin:0 0 1rem">Contact</h3><div class="p-field" style="margin-bottom:1rem"><label class="p-label">Email</label><input class="p-input" placeholder="you@example.com"></div><button class="p-btn p-btn-primary" style="width:100%">Submit</button></div>"#.into(),
            Kind::Button => r#"<div style="display:flex;gap:1rem;justify-content:center;padding:1rem"><button class="p-btn p-btn-primary">Primary</button><button class="p-btn p-btn-secondary">Secondary</button></div>"#.into(),
            Kind::Table => r#"<table class="p-table" style="max-width:36rem;margin:1rem auto"><thead><tr><th>Name</th><th>Status</th><th>Amount</th></tr></thead><tbody><tr><td>Alpha</td><td>active</td><td>$420</td></tr><tr><td>Beta</td><td>pending</td><td>$69</td></tr></tbody></table>"#.into(),
            Kind::Footer => r#"<footer style="padding:2rem;text-align:center;color:var(--p-text2);border-top:1px solid var(--p-border);font-size:.85rem">(c) 2026 Your Company - built with Polish</footer>"#.into(),
        }
    }
    fn code(&self) -> String {
        format!("    // {}\n    w.raw(r#\"{}\"#);\n", self.name(), self.html())
    }
}

struct Design { items: Vec<Kind>, theme: BuiltinTheme }

type Shared = Arc<Mutex<Design>>;

fn theme_name(t: &BuiltinTheme) -> &'static str {
    match t { BuiltinTheme::GlassHud=>"GlassHud", BuiltinTheme::Clean=>"Clean", BuiltinTheme::Enterprise=>"Enterprise" }
}

fn generated_code(d: &Design) -> String {
    let mut body = String::new();
    for k in &d.items { body.push_str(&k.code()); }
    format!(
"use polish_core::HtmlWriter;
use polish_style::{{BuiltinTheme, StyleSheet}};

/// Generated by Polish Designer — theme: {theme}
pub fn render_page() -> String {{
    let theme = BuiltinTheme::{theme}.theme();
    let css = StyleSheet::generate(&theme);
    let mut w = HtmlWriter::new();
{body}    let body = w.finish();
    format!(\"<!DOCTYPE html><html class='{{}}'><head><meta charset='utf-8'><style>{{}}</style></head><body>{{}}</body></html>\",
        css.theme_class, css.css, body)
}}
", theme = theme_name(&d.theme), body = body)
}

fn designer_page(d: &Design) -> String {
    let chrome_css = StyleSheet::generate(&BuiltinTheme::GlassHud.theme());
    let preview_css = StyleSheet::generate(&d.theme.theme());
    let palette: String = Kind::all().iter().map(|k| format!(
        r#"<form method="post" action="/add/{0}" style="margin:0"><button class="p-btn p-btn-secondary" style="width:100%;margin-bottom:.5rem">+ {0}</button></form>"#, k.name())).collect();
    let themes: String = ["GlassHud","Clean","Enterprise"].iter().map(|t| {
        let active = if *t == theme_name(&d.theme) { "p-btn-primary" } else { "p-btn-secondary" };
        format!(r#"<form method="post" action="/theme/{t}" style="margin:0;display:inline"><button class="p-btn {active}" style="font-size:.75rem;padding:.3rem .6rem">{t}</button></form>"#)
    }).collect();
    let layers: String = if d.items.is_empty() { "<p style='color:var(--p-text2);font-size:.8rem'>empty — add components</p>".into() } else {
        d.items.iter().enumerate().map(|(i,k)| format!(
        r#"<div style="display:flex;gap:.3rem;align-items:center;margin-bottom:.35rem;font-size:.8rem"><span style="flex:1">{n}. {name}</span><form method="post" action="/up/{n0}" style="margin:0"><button class="p-btn p-btn-secondary" style="padding:0 .4rem;font-size:.7rem">^</button></form><form method="post" action="/down/{n0}" style="margin:0"><button class="p-btn p-btn-secondary" style="padding:0 .4rem;font-size:.7rem">v</button></form><form method="post" action="/remove/{n0}" style="margin:0"><button class="p-btn p-btn-secondary" style="padding:0 .4rem;font-size:.7rem">x</button></form></div>"#,
        n=i+1, n0=i, name=k.name())).collect()
    };
    let preview: String = d.items.iter().map(|k| k.html()).collect();
    let code = escape_html(&generated_code(d));
    format!(r#"<!DOCTYPE html>
<html lang="en" class="{chrome_class}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="data:,">
<title>Polish Designer</title>
<style>
{chrome_css}
{preview_css}
html,body{{margin:0;min-height:100%}}
.pd-grid{{display:grid;grid-template-columns:200px 1fr 420px;gap:0;height:calc(100vh - 53px)}}
.pd-col{{overflow-y:auto;padding:1rem;border-right:1px solid var(--p-border)}}
.pd-preview{{background:var(--p-bg);}}
.pd-code{{font:11px/1.5 ui-monospace,monospace;white-space:pre-wrap;word-break:break-all;color:var(--p-text2)}}
</style></head>
<body>
<nav class="p-header" style="display:flex;align-items:center;gap:1.5rem;padding:.8rem 1.5rem;border-bottom:1px solid var(--p-border)">
  <span class="p-header-title" style="font-weight:700">Polish Designer</span>
  <div style="display:flex;gap:.4rem">{themes}</div>
  <div style="margin-left:auto;display:flex;gap:.6rem">
    <form method="post" action="/clear" style="margin:0"><button class="p-btn p-btn-secondary" style="font-size:.75rem">clear</button></form>
    <a class="p-btn p-btn-primary" style="font-size:.75rem;text-decoration:none" href="/export">export .rs</a>
  </div>
</nav>
<div class="pd-grid">
  <div class="pd-col"><h4 style="margin:0 0 .8rem;font-size:.8rem;text-transform:uppercase;color:var(--p-text2)">Components</h4>{palette}
  <h4 style="margin:1.2rem 0 .8rem;font-size:.8rem;text-transform:uppercase;color:var(--p-text2)">Layers</h4>{layers}</div>
  <div class="pd-col pd-preview"><div class="{preview_class}">{preview}</div></div>
  <div class="pd-col"><h4 style="margin:0 0 .8rem;font-size:.8rem;text-transform:uppercase;color:var(--p-text2)">Generated Rust</h4><div class="pd-code">{code}</div></div>
</div>
</body></html>"#,
        chrome_class = chrome_css.theme_class,
        chrome_css = chrome_css.css,
        preview_css = preview_css.css,
        preview_class = preview_css.theme_class,
    )
}

async fn home(State(s): State<Shared>) -> Html<String> { Html(designer_page(&s.lock().unwrap())) }

async fn add(State(s): State<Shared>, Path(kind): Path<String>) -> Redirect {
    if let Some(k) = Kind::from(&kind) { s.lock().unwrap().items.push(k); }
    Redirect::to("/")
}
async fn remove(State(s): State<Shared>, Path(i): Path<usize>) -> Redirect {
    let mut d = s.lock().unwrap(); if i < d.items.len() { d.items.remove(i); } Redirect::to("/")
}
async fn up(State(s): State<Shared>, Path(i): Path<usize>) -> Redirect {
    let mut d = s.lock().unwrap(); if i > 0 && i < d.items.len() { d.items.swap(i, i-1); } Redirect::to("/")
}
async fn down(State(s): State<Shared>, Path(i): Path<usize>) -> Redirect {
    let mut d = s.lock().unwrap(); if i+1 < d.items.len() { d.items.swap(i, i+1); } Redirect::to("/")
}
async fn theme(State(s): State<Shared>, Path(t): Path<String>) -> Redirect {
    let mut d = s.lock().unwrap();
    d.theme = match t.as_str() { "Clean"=>BuiltinTheme::Clean, "Enterprise"=>BuiltinTheme::Enterprise, _=>BuiltinTheme::GlassHud };
    Redirect::to("/")
}
async fn clear(State(s): State<Shared>) -> Redirect { s.lock().unwrap().items.clear(); Redirect::to("/") }

async fn export(State(s): State<Shared>) -> Response {
    let code = generated_code(&s.lock().unwrap());
    ([("Content-Type","text/plain; charset=utf-8"),("Content-Disposition","attachment; filename=\"polish_page.rs\"")], code).into_response()
}

#[tokio::main]
async fn main() {
    let state: Shared = Arc::new(Mutex::new(Design { items: vec![Kind::Navbar, Kind::Hero, Kind::Card], theme: BuiltinTheme::GlassHud }));
    let app = Router::new()
        .route("/", get(home))
        .route("/add/{kind}", post(add))
        .route("/remove/{i}", post(remove))
        .route("/up/{i}", post(up))
        .route("/down/{i}", post(down))
        .route("/theme/{t}", post(theme))
        .route("/clear", post(clear))
        .route("/export", get(export))
        .with_state(state);
    let addr = "0.0.0.0:3140";
    println!("Polish Designer listening on http://localhost:3140");
    let listener = tokio::net::TcpListener::bind(addr).await.expect("bind 3100");
    axum::serve(listener, app).await.expect("serve");
}
